kind: pipeline
name: build & release

steps:
- name: fetch tags
  image: docker:git
  commands:
    - git fetch --tags
  when:
    event: tag
- name: test
  image: golang:1.14
  commands:
    - go test -v ./internal/gemini
  when:
    event:
      exclude:
      - tag
- name: release
  image: golang:1.15
  environment:
    GITEA_TOKEN:
      from_secret: goreleaser_gitea_token
  commands:
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag
- name: build docker image
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: registry.git.tdem.in/gmnhg
    registry: registry.git.tdem.in
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
      - latest
  when:
    event:
    - tag

