name: Run tests

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tests
        run: go test -v ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
